version: 1
strains:
  - code:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: test-map-strains
    content:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: helix-cli
    static:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: test-map-strains
      path: /htdocs
    directoryIndex: index.html
    package: acapt/github-com--adobe--project-helix-io--test-map-strains-dirty
    name: client
    urls:
      - https://alex.helix-demo.xyz/client
    url: https://alex.helix-demo.xyz/client
  - code:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: test-map-strains
    content:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: helix-pipeline
    static:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: test-map-strains
      path: /htdocs
    directoryIndex: index.html
    package: acapt/github-com--adobe--project-helix-io--test-map-strains-dirty
    name: pipeline
    urls:
      - https://alex.helix-demo.xyz/pipeline
    url: https://alex.helix-demo.xyz/pipeline
  - code:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: test-map-strains
    content:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: helix-shared
    static:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: test-map-strains
      path: /htdocs
    directoryIndex: index.html
    package: acapt/github-com--adobe--project-helix-io--test-map-strains-dirty
    name: shared
    urls:
      - https://alex.helix-demo.xyz/shared
    url: https://alex.helix-demo.xyz/shared
  - code:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: test-map-strains
    content:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: test-map-strains
    static:
      protocol: https
      host: github.com
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: test-map-strains
      path: /htdocs
    directoryIndex: index.html
    package: acapt/github-com--adobe--project-helix-io--test-map-strains-dirty
    name: default
    urls:
      - https://alex.helix-demo.xyz/
    url: https://alex.helix-demo.xyz/
  - code:
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: ""
    content:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: helix-cli
      ref: ""
      path: ""
    static:
      magic: false
      allow: []
      deny: []
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: /htdocs
    directoryIndex: index.html
    package: ""
    name: clientDev
    sticky: false
    condition: ""
    perf:
      device: ""
      location: ""
      connection: ""
    urls:
      - http://localhost:3000/client
    url: http://localhost:3000/client
  - code:
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: ""
    content:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: helix-pipeline
      ref: ""
      path: ""
    static:
      magic: false
      allow: []
      deny: []
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: /htdocs
    directoryIndex: index.html
    package: ""
    name: pipelineDev
    sticky: false
    condition: ""
    perf:
      device: ""
      location: ""
      connection: ""
    urls:
      - http://localhost:3000/pipeline
    url: http://localhost:3000/pipeline
  - code:
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: ""
    content:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: helix-shared
      ref: ""
      path: ""
    static:
      magic: false
      allow: []
      deny: []
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: /htdocs
    directoryIndex: index.html
    package: ""
    name: sharedDev
    sticky: false
    condition: ""
    perf:
      device: ""
      location: ""
      connection: ""
    urls:
      - http://localhost:3000/shared
    url: http://localhost:3000/shared
  - code:
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: ""
    content:
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: ""
    static:
      magic: false
      allow: []
      deny: []
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: /htdocs
    directoryIndex: index.html
    package: ""
    name: defaultDev
    sticky: false
    condition: ""
    perf:
      device: ""
      location: ""
      connection: ""
    urls:
      - http://localhost:3000/
    url: http://localhost:3000/
