# Copyright 2018 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.
version: 1

definitions:
  defaults:
    - &defaultRepo https://github.com/adobe/project-helix.io.git#main
  strains:
    base:
      &basestrain
      code: *defaultRepo
      content: *defaultRepo
      static: *defaultRepo

strains:
  - name: client
    <<: *basestrain
    condition:
      url.path: /client
    content: https://github.com/adobe/helix-cli.git#main
    package: helix-pages/06307d78c1b25b9871803e56cdc1917835592835

  - name: pipeline
    <<: *basestrain
    condition:
      url.path: /pipeline
    content: https://github.com/adobe/helix-pipeline.git#main
    package: helix-pages/06307d78c1b25b9871803e56cdc1917835592835

  - name: shared
    <<: *basestrain
    condition:
      url.path: /shared
    content: https://github.com/adobe/helix-shared.git#main
    package: helix-pages/06307d78c1b25b9871803e56cdc1917835592835

  - name: default
    <<: *basestrain
    package: helix-pages/06307d78c1b25b9871803e56cdc1917835592835
