version: 1
strains:
  - code:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: master
      path: ""
    content:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: helix-cli
      ref: ""
      path: ""
    static:
      magic: false
      allow: []
      deny: []
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: master
      path: /htdocs
    directoryIndex: index.html
    package: acapt/e0cf9a737a7819cf835efc3777cc4b826fce54a5
    name: client
    sticky: false
    condition: ""
    perf:
      device: ""
      location: ""
      connection: ""
    urls:
      - https://www.project-helix.io/client
    url: https://www.project-helix.io/client
  - code:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: master
      path: ""
    content:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: helix-pipeline
      ref: ""
      path: ""
    static:
      magic: false
      allow: []
      deny: []
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: master
      path: /htdocs
    directoryIndex: index.html
    package: acapt/e0cf9a737a7819cf835efc3777cc4b826fce54a5
    name: pipeline
    sticky: false
    condition: ""
    perf:
      device: ""
      location: ""
      connection: ""
    urls:
      - https://www.project-helix.io/pipeline
    url: https://www.project-helix.io/pipeline
  - code:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: master
      path: ""
    content:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: helix-shared
      ref: ""
      path: ""
    static:
      magic: false
      allow: []
      deny: []
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: master
      path: /htdocs
    directoryIndex: index.html
    package: acapt/e0cf9a737a7819cf835efc3777cc4b826fce54a5
    name: shared
    sticky: false
    condition: ""
    perf:
      device: ""
      location: ""
      connection: ""
    urls:
      - https://www.project-helix.io/shared
    url: https://www.project-helix.io/shared
  - code:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: master
      path: ""
    content:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: master
      path: ""
    static:
      magic: false
      allow: []
      deny: []
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: project-helix.io
      ref: master
      path: /htdocs
    directoryIndex: index.html
    package: acapt/e0cf9a737a7819cf835efc3777cc4b826fce54a5
    name: default
    sticky: false
    condition: ""
    perf:
      device: ""
      location: ""
      connection: ""
    urls:
      - https://www.project-helix.io/
    url: https://www.project-helix.io/
  - code:
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: ""
    content:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: helix-cli
      ref: ""
      path: ""
    static:
      magic: false
      allow: []
      deny: []
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: /htdocs
    directoryIndex: index.html
    package: ""
    name: clientDev
    sticky: false
    condition: ""
    perf:
      device: ""
      location: ""
      connection: ""
    urls:
      - http://localhost:3000/client
    url: http://localhost:3000/client
  - code:
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: ""
    content:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: helix-pipeline
      ref: ""
      path: ""
    static:
      magic: false
      allow: []
      deny: []
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: /htdocs
    directoryIndex: index.html
    package: ""
    name: pipelineDev
    sticky: false
    condition: ""
    perf:
      device: ""
      location: ""
      connection: ""
    urls:
      - http://localhost:3000/pipeline
    url: http://localhost:3000/pipeline
  - code:
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: ""
    content:
      protocol: https
      host: github.com
      port: ""
      hostname: github.com
      owner: adobe
      repo: helix-shared
      ref: ""
      path: ""
    static:
      magic: false
      allow: []
      deny: []
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: /htdocs
    directoryIndex: index.html
    package: ""
    name: sharedDev
    sticky: false
    condition: ""
    perf:
      device: ""
      location: ""
      connection: ""
    urls:
      - http://localhost:3000/shared
    url: http://localhost:3000/shared
  - code:
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: ""
    content:
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: ""
    static:
      magic: false
      allow: []
      deny: []
      protocol: http
      host: localhost
      port: ""
      hostname: localhost
      owner: local
      repo: default
      ref: ""
      path: /htdocs
    directoryIndex: index.html
    package: ""
    name: defaultDev
    sticky: false
    condition: ""
    perf:
      device: ""
      location: ""
      connection: ""
    urls:
      - http://localhost:3000/
    url: http://localhost:3000/
